### ISSUE TITLE
Navigation rework

### ISSUE THREAD

**Issue by lucasgautheron** [lucasgautheron/CosmologyWebsite#23]
- Generate static pages for every (content, appendix) request
- Set URL format to /content/url-friendly-content-name/appendix/url-friendly-appendix-name/
- Use JS if available to load content dynamically
- Make sure prev and next use this URL format
- Bind left and right arrow to prev and next

@ScalaWilliam probably knows better what would work best

**Comment by ScalaWilliam** [comment]
nono, static only for (content); load appendix dynamically still (it's not the core of the content). 
Url format should use /url-friendly-content/?appendix=appendix-name

Might want to use prefetch for optimisation or even service workers, but I think they're unnecessary.

**Comment by lucasgautheron** [comment]
Static only for content is fine.
Dynamic if possible for appendix is great.
Still should be an static alternative for appendices.
